### ISSUE TITLE
Gaining 'root' access

### ISSUE THREAD

**Issue by roacobb** [fisma-ready/ubuntu-lts#26]
To gain 'root' access use 'sudo su -'

**Comment by gregelin** [comment]
@konklone, I was chatting with @roacobb about this.

I think there is a guiding principle for documentation of an FISMA-ready vm that encourages including this information in this repository's documentation.

The principle is: the virtual machine repository provides sufficient information to enable a wide range of individuals to easily and confidently use the virtual machine in it is accreditation-ready state; common gotchas to the occasional system-admin should be communicated in the repo itself.

Imagine the scenario in which Jessie, government developer, wants to use fisma-ready/ubuntu-lts on AWS but Chris, the agency admin asked to consider Jessie's request, has only used RHEL in the own data center. Chris, who is unfamiliar with both Ubuntu and AWS, could reasonably be confused by the fact AWS images do not have root password initially in place. Jessie, who only occasionally does Unix sys-admin tasks always has to google how to set up root on AWS. Root access is necessary to check configuration details, however. Therefore, including a snippet about establishing root on fisma-ready/ubuntu-lts makes it easier for both Jessie and Chris to use the vm, and makes it easier to test the fisma-readiness and provide Chris with confidence that the virtual-machine is properly hardened in accordance with the description in the repo.

**Comment by konklone** [comment]
@gregelin, I totally get what you mean. We should make sure this project is welcoming and useful to people unfamiliar with the specifics of Ubuntu and AWS.

I am concerned about running down the slippery slope of documenting the general concepts of how Ubuntu works. There's a lot. 

What I think we could and should do is link to the resources that Ubuntu and third parties have already written out there. For example, Digital Ocean has [almost 500 tutorials related to Ubuntu](https://www.digitalocean.com/community/tags/ubuntu?primary_filter=tutorials), and they're generally pretty high quality.

Where there's something specific to the hardening we've done on FISMA Ready, that makes completely obvious sense to document first-party.

Thoughts?

**Comment by NoahKunin** [comment]
@konklone concur.

**Comment by gregelin** [comment]
@konklone @roacobb @NoahKunin That's a good approach. We could have a link to a common set of tutorials that would bey hyper useful to individuals working with this and other fisma-ready repos. Maybe some that already exists and a general one to help people get started.
