### ISSUE TITLE
Error creating AMI: InvalidBlockDeviceMapping: /dev/sdk is being assigned to multiple times.

### ISSUE THREAD

**Issue by jzonthemtn** [fisma-ready/ubuntu-lts#38]
I'm hitting the following error when running ami.sh:

```
==> amazon-ebs: Creating the AMI: FISMA Ready Baseline Ubuntu (1436972778 - Packer)
==> amazon-ebs: Error creating AMI: InvalidBlockDeviceMapping: /dev/sdk is being assigned to multiple times.
==> amazon-ebs: 	status code: 400, request id: []
==> amazon-ebs: Terminating the source AWS instance...
```

It is launching an m3.medium. I added the subnet and VPC ID to packer.json since I am not using a default VPC. Is there anything that I am missing or forgetting to do?

Thanks

**Comment by ozzyjohnson** [comment]
@jzonthemtn - I'm unable to recreate this. Can you provide any additional information?

In the meantime, perhaps you can give the `multi-ebs` branch a try. Using multiple EBS volumes as is done there is direction I'd like to take this as it's a good bit more flexible than the partitioning done in `master`.

**Comment by jzonthemtn** [comment]
Not at the moment but I will go back over and make sure I followed all the instructions correctly. Yes, I will give that branch a try. Thanks!

**Comment by jzonthemtn** [comment]
Sorry for the long delay! Today I went back and read the instructions again. The first time I had packer 0.8.5 (I believe) and the instructions say 0.7.5. When I changed to packer 0.7.5 it worked perfectly. Thanks!
