### ISSUE TITLE
If I wanted to run a smaller instance than m3.medium (say t2.micro) could I still do so as long as I update the package.json with a change of instance size?

### ISSUE THREAD

**Issue by stroupaloop** [fisma-ready/ubuntu-lts#41]

**Comment by konklone** [comment]
I think that'd be just fine.

**Comment by konklone** [comment]
And if you want to submit a PR that makes it possible to override the default size on the command line or something, so that others can do it without changing the code locally, that'd be most welcome.

**Comment by stroupaloop** [comment]
@konklone  to the rescue ;)

**Comment by stroupaloop** [comment]
Interestingly enough, just tried to run this on a t2.micro (post a very long XCode update) and received the following error

![image](https://cloud.githubusercontent.com/assets/2424551/10989936/af5b1aea-841b-11e5-8acc-d04234f3ee0c.png)

Seeing if I can add in the values into the package.json

**Comment by stroupaloop** [comment]
Don't receive this error when running a m3.medium since t2.micro is an EBS only instance. Can't find the documentation on how to modify the package.json appropriately, but thought I'd share, still digging.

**Comment by konklone** [comment]
Reading the error literally, it looks like that instance size can only be launched into a VPC. Could be our script is launching the instance into EC2-classic (which makes sense, if no VPC is specified). So, one way to resolve this would be to provide a mechanism for a VPC ID to be provided over the command line, for instance types which require one.

**Comment by stroupaloop** [comment]
had to add to the following after the instance_type

````
"instance_type": "t2.micro",
"subnet_id" : "subnet-xxxxxxx",
"security_group_id": "sg-xxxxxxx",
````

to get it to work

**Comment by stroupaloop** [comment]
Was able to successfully create a t2.micro server based on the settings, but now face this issue when trying to start the server

![image](https://cloud.githubusercontent.com/assets/2424551/10990594/db8f9062-8422-11e5-8466-1a70878ed558.png)

**Comment by konklone** [comment]
That's super strange. It's not obvious to me what that is. @ozzyjohnson, any ideas?

**Comment by stroupaloop** [comment]
@konklone that was my bad. What I was trying to do was start the temp EC2 instance that was used to create the AMI. I'm booting a new EC2 instance using the AMI created running a t2.micro.

**Comment by konklone** [comment]
Ah, makes sense. :+1:

(For future reference though, I think it's better not to delete past comments/images, even if they proved to be a mistake of some sort -- the thread is incomplete now, and doesn't show what we were talking about.)

**Comment by stroupaloop** [comment]
Yeah fair point ... also, I realized that the purpose of this EC2 instance being spun up is to simply create an AMI image (missed that in that late night hours) so I suppose it doesn't matter if you use a m3.medium or t2.micro during creation as it's only up for a few seconds.

I'd say since the t2.micro requires a specified security group and subnet that it makes sense to not use it.
